/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package guia1_ej4;

import java.util.TreeSet;

/**
 *
 * @author pmora
 */
public class Menu extends javax.swing.JFrame {
public static TreeSet<Producto> listaProductos= new TreeSet<>();
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        cargarProductos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmPorRubro = new javax.swing.JMenuItem();
        jmPorNombre = new javax.swing.JMenuItem();
        jmPorPrecio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 935, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 627, Short.MAX_VALUE)
        );

        jMenu1.setText("Administracion");

        jMenuItem1.setText("Productos");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Consultas");

        jmPorRubro.setText("Por rubro");
        jmPorRubro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmPorRubroActionPerformed(evt);
            }
        });
        jMenu2.add(jmPorRubro);

        jmPorNombre.setText("Por nombre");
        jmPorNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmPorNombreActionPerformed(evt);
            }
        });
        jMenu2.add(jmPorNombre);

        jmPorPrecio.setText("Por precio");
        jmPorPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmPorPrecioActionPerformed(evt);
            }
        });
        jMenu2.add(jmPorPrecio);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmPorNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmPorNombreActionPerformed
        
        escritorio.removeAll();
        escritorio.repaint();
        BusquedaPorNombre bpn = new BusquedaPorNombre();
        bpn.setVisible(true);
        escritorio.add(bpn);
        escritorio.moveToFront(bpn);
        
        
    }//GEN-LAST:event_jmPorNombreActionPerformed

    private void jmPorPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmPorPrecioActionPerformed
        escritorio.removeAll();
       escritorio.repaint();
       BusquedaPorPrecio bpp = new BusquedaPorPrecio();
       bpp.setVisible(true);
       escritorio.add(bpp);
       escritorio.moveToFront(bpp);
    }//GEN-LAST:event_jmPorPrecioActionPerformed

    private void jmPorRubroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmPorRubroActionPerformed
       escritorio.removeAll();
       escritorio.repaint();
       BusquedaPorRubro bpr = new BusquedaPorRubro();
       bpr.setVisible(true);
       escritorio.add(bpr);
       escritorio.moveToFront(bpr);
    }//GEN-LAST:event_jmPorRubroActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       escritorio.removeAll();
       escritorio.repaint();
       ProductosAdministracion pa = new ProductosAdministracion();
       pa.setVisible(true);
       escritorio.add(pa);
       escritorio.moveToFront(pa);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jmPorNombre;
    private javax.swing.JMenuItem jmPorPrecio;
    private javax.swing.JMenuItem jmPorRubro;
    // End of variables declaration//GEN-END:variables

    private void cargarProductos(){
       
        listaProductos.add(new Producto(10, "Azucar x kilo", 200, 6, Categoria.Comestible));
        listaProductos.add(new Producto(5, "Aceite de girazol x litro", 800, 10, Categoria.Comestible));
        listaProductos.add(new Producto(3, "Yerba x kilo", 1200, 8, Categoria.Comestible));
        listaProductos.add(new Producto(4, "Limpiador", 1200, 8, Categoria.Limpieza));
        listaProductos.add(new Producto(8, "Perfume", 1600, 7, Categoria.Perfumeria));
        listaProductos.add(new Producto(60, "Perfume 2", 300, 20, Categoria.Perfumeria));
        
    }


}
